import { describe, expect, it } from "vitest";
import {
  calculateChangedLineCount,
  generateBeforeAfterDiff,
} from "@/lib/ai/filesystem/diff-utils";

describe("diff-utils", () => {
  it("counts the changed hunk lines generated by generateBeforeAfterDiff", () => {
    const before = `line1
line2
line3
line4
line5
line6
line7`;
    const after = `line1
line2
LINE3
line4
line5
line6
line7`;

    const diff = generateBeforeAfterDiff("example.txt", before, after);

    expect(calculateChangedLineCount(before, after)).toBe(1);
    expect(diff).toContain("@@ -3,1 +3,1 @@");
    expect(diff).toContain("3 | - line3");
    expect(diff).toContain("3 | + LINE3");
  });

  it("counts insertions and deletions by the larger side of the trimmed hunk", () => {
    const before = `line1
line2
line4`;
    const after = `line1
line2
line3
line3b
line4`;

    expect(calculateChangedLineCount(before, after)).toBe(2);
  });

  it("returns zero for identical content", () => {
    const content = `line1
line2`;

    expect(calculateChangedLineCount(content, content)).toBe(0);
  });
});
