/**
 * Sprint 5 — TS path-alias resolution for the design-workspace `import`
 * action.
 *
 * The user-visible bug these tests pin: importing a real `.tsx` from a
 * synced folder that uses `@/*` aliases (e.g. `import { cn } from
 * "@/lib/utils"`) failed with `Could not resolve "@/lib/utils"` because
 * the workspace bundler ignored the host project's tsconfig paths.
 *
 * Coverage:
 *   - `findOwningSyncedFolder` — longest-prefix match across overlapping
 *     synced folders, plus the no-match path.
 *   - `loadTsconfigPaths` — reads a real `tsconfig.json` (with
 *     `compilerOptions.paths`) from a tmpdir, honors the implicit
 *     `baseUrl` fall-back when the file omits it, and returns `null`
 *     when no aliases are configured.
 *   - `createTsconfigPathsPlugin` driven through the real esbuild
 *     pipeline against a tmpdir fixture: the alias resolves to a real
 *     file, transitive imports survive, and a typo in the alias still
 *     surfaces as an esbuild "Could not resolve" diagnostic (we never
 *     silently swallow misses).
 *   - End-to-end through `buildTailwindPreviewWithMetadata` with the
 *     `tsconfigPaths` option set: the compiled preview HTML contains
 *     the resolved utility's output, mirroring how `handleImport`
 *     wires the option for real imports.
 */

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import * as esbuild from "esbuild";

import {
  createTsconfigPathsPlugin,
  findOwningSyncedFolder,
  loadTsconfigPaths,
} from "../tsconfig-paths";
import { buildTailwindPreviewWithMetadata } from "../compiler";

// --------------------------------------------------------------------------
// findOwningSyncedFolder
// --------------------------------------------------------------------------
describe("findOwningSyncedFolder", () => {
  it("returns the longest matching prefix when folders nest", () => {
    const folders = ["/repo", "/repo/sub", "/elsewhere"];
    expect(
      findOwningSyncedFolder("/repo/sub/components/foo.tsx", folders),
    ).toBe("/repo/sub");
  });

  it("matches the exact folder root", () => {
    const folders = ["/repo"];
    expect(findOwningSyncedFolder("/repo", folders)).toBe("/repo");
  });

  it("returns null when the file lives outside every folder", () => {
    expect(
      findOwningSyncedFolder("/other/foo.tsx", ["/repo", "/elsewhere"]),
    ).toBeNull();
  });

  it("rejects a near-prefix that is not a path boundary", () => {
    // /repo-other should NOT be claimed by /repo. The trailing-separator
    // guard inside findOwningSyncedFolder is the reason this passes.
    expect(findOwningSyncedFolder("/repo-other/foo.tsx", ["/repo"])).toBeNull();
  });
});

// --------------------------------------------------------------------------
// loadTsconfigPaths + createTsconfigPathsPlugin (esbuild integration)
// --------------------------------------------------------------------------
describe("loadTsconfigPaths + createTsconfigPathsPlugin (real esbuild)", () => {
  let workdir: string;

  beforeEach(() => {
    workdir = mkdtempSync(join(tmpdir(), "selene-tsconfig-paths-"));
  });

  afterEach(() => {
    rmSync(workdir, { recursive: true, force: true });
  });

  function writeFixture(files: Record<string, string>): void {
    for (const [relPath, contents] of Object.entries(files)) {
      const abs = join(workdir, relPath);
      mkdirSync(join(abs, ".."), { recursive: true });
      writeFileSync(abs, contents, "utf8");
    }
  }

  it("loads compilerOptions.paths and falls back to the tsconfig dir for baseUrl", () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({
        compilerOptions: {
          // Intentionally omit baseUrl — TS treats it as the tsconfig dir
          // under moduleResolution: "bundler", which is the most common
          // shape in synced folders generated by `create-next-app`.
          paths: { "@/*": ["./*"] },
        },
      }),
    });

    const config = loadTsconfigPaths(workdir);
    expect(config).not.toBeNull();
    expect(config?.baseUrl).toBe(workdir);
    expect(config?.paths).toEqual({ "@/*": ["./*"] });
  });

  it("returns null when no paths config is declared", () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({ compilerOptions: {} }),
    });
    expect(loadTsconfigPaths(workdir)).toBeNull();
  });

  it("returns null when the tsconfig file is missing", () => {
    expect(loadTsconfigPaths(workdir)).toBeNull();
  });

  it("resolves @/lib/utils through esbuild against the synced folder root", async () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { paths: { "@/*": ["./*"] } },
      }),
      "lib/utils.ts": `export const cn = (...parts: Array<string | false>) => parts.filter(Boolean).join(" ");`,
      "entry.ts": `import { cn } from "@/lib/utils"; export const result = cn("a", "b");`,
    });

    const config = loadTsconfigPaths(workdir);
    expect(config).not.toBeNull();

    const result = await esbuild.build({
      entryPoints: [join(workdir, "entry.ts")],
      bundle: true,
      write: false,
      format: "iife",
      globalName: "Probe",
      logLevel: "silent",
      plugins: [createTsconfigPathsPlugin(config!)],
    });

    expect(result.errors).toHaveLength(0);
    const code = result.outputFiles[0]?.text ?? "";
    // The resolved utility's body should be inlined into the bundle.
    expect(code).toContain("filter(Boolean)");
    expect(code).toContain('.join(" ")');
  });

  it("resolves transitive @/components/foo → @/lib/utils chains", async () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { paths: { "@/*": ["./*"] } },
      }),
      "lib/utils.ts": `export const tag = "lib-utils-marker";`,
      "components/foo.ts": `export { tag as foo } from "@/lib/utils";`,
      "entry.ts": `export { foo } from "@/components/foo";`,
    });

    const config = loadTsconfigPaths(workdir)!;
    const result = await esbuild.build({
      entryPoints: [join(workdir, "entry.ts")],
      bundle: true,
      write: false,
      format: "iife",
      globalName: "Probe",
      logLevel: "silent",
      plugins: [createTsconfigPathsPlugin(config)],
    });
    expect(result.errors).toHaveLength(0);
    expect(result.outputFiles[0]?.text).toContain("lib-utils-marker");
  });

  it("preserves the esbuild error path when the alias target is missing", async () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { paths: { "@/*": ["./*"] } },
      }),
      "entry.ts": `import { cn } from "@/lib/missing"; export const result = cn();`,
    });

    const config = loadTsconfigPaths(workdir)!;
    let thrown: unknown;
    try {
      await esbuild.build({
        entryPoints: [join(workdir, "entry.ts")],
        bundle: true,
        write: false,
        format: "iife",
        globalName: "Probe",
        logLevel: "silent",
        plugins: [createTsconfigPathsPlugin(config)],
      });
    } catch (error) {
      thrown = error;
    }
    expect(thrown).toBeDefined();
    const err = thrown as { errors?: Array<{ text: string }> };
    expect(err.errors?.length ?? 0).toBeGreaterThan(0);
    // The text mentions the original alias so the user can fix the typo.
    expect(err.errors?.[0]?.text ?? "").toMatch(/@\/lib\/missing/);
  });

  it("ignores bare-package specifiers (react, framer-motion, …) and lets esbuild handle them", async () => {
    writeFixture({
      "tsconfig.json": JSON.stringify({
        compilerOptions: { paths: { "@/*": ["./*"] } },
      }),
      "lib/utils.ts": `export const cn = () => "ok";`,
      "entry.ts": `import { cn } from "@/lib/utils"; import { something } from "non-existent-pkg"; export { cn, something };`,
    });

    const config = loadTsconfigPaths(workdir)!;
    let thrown: unknown;
    try {
      await esbuild.build({
        entryPoints: [join(workdir, "entry.ts")],
        bundle: true,
        write: false,
        format: "iife",
        globalName: "Probe",
        logLevel: "silent",
        plugins: [createTsconfigPathsPlugin(config)],
      });
    } catch (error) {
      thrown = error;
    }
    // The failure must be attributed to the bare package, NOT the alias —
    // confirms the alias plugin doesn't shadow esbuild's default resolver
    // for non-matching specifiers.
    expect(thrown).toBeDefined();
    const err = thrown as { errors?: Array<{ text: string }> };
    expect(err.errors?.[0]?.text ?? "").toMatch(/non-existent-pkg/);
    expect(err.errors?.[0]?.text ?? "").not.toMatch(/@\/lib\/utils/);
  });
});

// --------------------------------------------------------------------------
// End-to-end through buildTailwindPreviewWithMetadata
//
// Mirrors how `handleImport` wires `tsconfigPaths` for real imports. We
// route through the public entry so any future re-ordering of plugins or
// option threading inside the compiler is caught here.
// --------------------------------------------------------------------------
describe("buildTailwindPreviewWithMetadata + tsconfigPaths (Sprint 5)", () => {
  let workdir: string;

  beforeEach(() => {
    workdir = mkdtempSync(join(tmpdir(), "selene-tsconfig-paths-e2e-"));
  });

  afterEach(() => {
    rmSync(workdir, { recursive: true, force: true });
  });

  it("compiles a component that imports a synced-folder utility via @/*", async () => {
    // The utility lives in the synced folder so the plugin must resolve
    // `@/lib/utils` against the folder root, not against PROJECT_ROOT.
    writeFileSync(
      join(workdir, "tsconfig.json"),
      JSON.stringify({ compilerOptions: { paths: { "@/*": ["./*"] } } }),
      "utf8",
    );
    mkdirSync(join(workdir, "lib"), { recursive: true });
    writeFileSync(
      join(workdir, "lib", "utils.ts"),
      `export const cn = (...parts: Array<string | false | null | undefined>) =>
         parts.filter(Boolean).join(" ");`,
      "utf8",
    );

    const componentSource = `
import React from "react";
import { cn } from "@/lib/utils";

export default function Card() {
  return (
    <div className={cn("p-4", "bg-blue-500", false && "hidden")}>
      <span>tsconfig-paths-marker</span>
    </div>
  );
}
`;

    const tsconfigPaths = loadTsconfigPaths(workdir);
    expect(tsconfigPaths).not.toBeNull();

    const { html, report } = await buildTailwindPreviewWithMetadata(
      componentSource,
      "Card",
      {
        tsconfigPaths: tsconfigPaths!,
        // The dependency installer is irrelevant here — the only
        // bare-package import is `react`, already in PROJECT_ROOT/node_modules.
        autoInstallMissingDependencies: false,
      },
    );

    expect(report.errors).toEqual([]);
    expect(html).toContain("tsconfig-paths-marker");
    // The transformed bundle includes the inlined utility; the marker
    // string from the utility's source should appear in the compiled HTML.
    expect(html).toContain("filter(Boolean)");
  }, 30_000);

  it("compiles @/* imports with transitive relative project imports", async () => {
    writeFileSync(
      join(workdir, "tsconfig.json"),
      JSON.stringify({ compilerOptions: { paths: { "@/*": ["./*"] } } }),
      "utf8",
    );
    mkdirSync(join(workdir, "lib"), { recursive: true });
    writeFileSync(
      join(workdir, "lib", "tokens.ts"),
      `export const token = "transitive-relative-marker";`,
      "utf8",
    );
    writeFileSync(
      join(workdir, "lib", "utils.ts"),
      `import { token } from "./tokens";
       export const cn = (...parts: Array<string | false | null | undefined>) =>
         [token, ...parts].filter(Boolean).join(" ");`,
      "utf8",
    );

    const componentSource = `
import React from "react";
import { cn } from "@/lib/utils";

export default function Card() {
  return <div className={cn("p-4")}>alias-relative-import-marker</div>;
}
`;

    const tsconfigPaths = loadTsconfigPaths(workdir);
    expect(tsconfigPaths).not.toBeNull();

    const { html, report } = await buildTailwindPreviewWithMetadata(
      componentSource,
      "Card",
      { tsconfigPaths: tsconfigPaths!, autoInstallMissingDependencies: false },
    );

    expect(report.errors).toEqual([]);
    expect(html).toContain("alias-relative-import-marker");
    expect(html).toContain("transitive-relative-marker");
  }, 30_000);

  it("compiles common Next.js imports through preview stubs", async () => {
    const componentSource = `
import React from "react";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter, useSearchParams } from "next/navigation";

export default function Card() {
  const router = useRouter();
  const pathname = usePathname();
  const params = useSearchParams();
  return (
    <Link href="/preview" onClick={() => router.prefetch("/preview")}>
      <Image src="/icon.png" alt="icon" width={16} height={16} />
      <span>next-preview-stub-marker {pathname} {params.get("q") || "none"}</span>
    </Link>
  );
}
`;

    const { html, report } = await buildTailwindPreviewWithMetadata(
      componentSource,
      "Card",
      { autoInstallMissingDependencies: false },
    );

    expect(report.errors).toEqual([]);
    expect(html).toContain("next-preview-stub-marker");
    expect(html).toContain('createElement("a"');
    expect(html).toContain('createElement("img"');
  }, 30_000);

  it("surfaces a real compile-report error when the alias target file is missing", async () => {
    writeFileSync(
      join(workdir, "tsconfig.json"),
      JSON.stringify({ compilerOptions: { paths: { "@/*": ["./*"] } } }),
      "utf8",
    );

    const componentSource = `
import React from "react";
import { cn } from "@/lib/missing-utility";

export default function Card() {
  return <div className={cn("p-4")}>x</div>;
}
`;

    const tsconfigPaths = loadTsconfigPaths(workdir)!;

    let thrown: unknown;
    try {
      await buildTailwindPreviewWithMetadata(componentSource, "Card", {
        tsconfigPaths,
        autoInstallMissingDependencies: false,
      });
    } catch (error) {
      thrown = error;
    }

    expect(thrown).toBeDefined();
    const err = thrown as Error & {
      report?: { errors?: Array<{ message?: string }> };
    };
    expect(err.name).toBe("DesignWorkspaceCompileError");
    expect(err.report?.errors?.length ?? 0).toBeGreaterThan(0);
    expect(err.report?.errors?.[0]?.message ?? "").toMatch(
      /@\/lib\/missing-utility/,
    );
  }, 30_000);
});
